/**
 * fix.js — dead-doctor
 *
 * Turns dead-code findings into SAFE, REVIEWABLE cleanup scripts. It never
 * deletes anything itself — it writes:
 *
 *   dead-doctor-cleanup.sh     git-rm + npm-uninstall for bash/zsh (macOS/Linux)
 *   dead-doctor-cleanup.ps1    same for PowerShell (Windows)
 *   dead-doctor-cleanup.md     a human-readable, reviewable plan
 *
 * Deterministic removals (dead files, empty files, zombie deps) become real
 * commands you can review then run. Judgment calls (unused exports, duplicates,
 * unreachable code) become clearly-marked manual TODOs.
 */

import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Build the cleanup plan from issues
// ---------------------------------------------------------------------------

export function buildPlan(issues) {
  const grouped = {};
  for (const i of issues) (grouped[i.rule] ??= []).push(i);

  // Files safe to remove outright: unreachable dead files + empty files
  const deletions = [];
  for (const i of grouped["dead-file"] ?? []) deletions.push({ file: i.file, why: "unreachable from any entry point" });
  for (const i of grouped["empty-file"] ?? []) deletions.push({ file: i.file, why: "empty / no meaningful content" });

  // Dead pages: remove the page + sibling route files (manual confirm)
  const deadPages = (grouped["dead-page"] ?? []).map((i) => i.file);

  // Zombie deps → npm uninstall
  const depRemovals = [];
  for (const i of grouped["zombie-dep"] ?? []) {
    const m = (i.snippet ?? "").match(/"([^"]+)"\s*:/);
    if (m) depRemovals.push(m[1]);
  }

  // Duplicates → keep one, re-import the rest (manual)
  const duplicates = (grouped["duplicate-file"] ?? []).map((i) => ({
    keep: i.duplicates?.[0] ?? i.file,
    remove: (i.duplicates ?? []).slice(1),
  }));

  // Manual edits (counts only — these touch code, not whole files)
  const manual = {
    unusedExports: (grouped["unused-export"] ?? []).length,
    unusedImports: (grouped["unused-import"] ?? []).length,
    commentBlocks: (grouped["comment-block"] ?? []).length,
    unreachable:   (grouped["unreachable-code"] ?? []).length,
  };

  return { deletions, deadPages, depRemovals, duplicates, manual };
}

// ---------------------------------------------------------------------------
// Renderers
// ---------------------------------------------------------------------------

function shHeader(title) {
  return [
    `# ${title}`,
    "# Generated by dead-doctor — review every line before running.",
    "# git tracks all deletions, so `git checkout` undoes anything here.",
    "set -e",
    "",
  ].join("\n");
}

export function renderBash(plan) {
  const out = [shHeader("dead-doctor cleanup (bash/zsh)")];

  if (plan.deletions.length) {
    out.push("# ── Remove dead & empty files ───────────────────────────────");
    for (const d of plan.deletions) out.push(`git rm "${d.file}"   # ${d.why}`);
    out.push("");
  }
  if (plan.depRemovals.length) {
    out.push("# ── Uninstall zombie dependencies ───────────────────────────");
    out.push(`npm uninstall ${plan.depRemovals.map((d) => `"${d}"`).join(" ")}`);
    out.push("");
  }
  if (plan.deadPages.length) {
    out.push("# ── Dead pages (confirm they're truly unlinked first) ───────");
    for (const f of plan.deadPages) out.push(`# git rm "${f}"   # plus any sibling layout/loading/error files`);
    out.push("");
  }
  if (plan.duplicates.length) {
    out.push("# ── Duplicate files (keep one, re-import the rest) ──────────");
    for (const d of plan.duplicates) {
      out.push(`# keep:   ${d.keep}`);
      for (const r of d.remove) out.push(`# git rm "${r}"   # then import from ${d.keep}`);
    }
    out.push("");
  }
  out.push(`# Manual edits still needed: ${plan.manual.unusedExports} unused exports, ` +
    `${plan.manual.unusedImports} unused imports, ${plan.manual.commentBlocks} comment blocks, ` +
    `${plan.manual.unreachable} unreachable blocks (see the report).`);
  out.push("");
  out.push("echo 'dead-doctor cleanup complete — re-run: npx dead-doctor'");
  return out.join("\n");
}

export function renderPowerShell(plan) {
  const out = [
    "# dead-doctor cleanup (PowerShell)",
    "# Generated by dead-doctor — review every line before running.",
    "$ErrorActionPreference = 'Stop'",
    "",
  ];
  if (plan.deletions.length) {
    out.push("# Remove dead & empty files");
    for (const d of plan.deletions) out.push(`git rm "${d.file}"   # ${d.why}`);
    out.push("");
  }
  if (plan.depRemovals.length) {
    out.push("# Uninstall zombie dependencies");
    out.push(`npm uninstall ${plan.depRemovals.join(" ")}`);
    out.push("");
  }
  if (plan.deadPages.length) {
    out.push("# Dead pages (confirm unlinked first)");
    for (const f of plan.deadPages) out.push(`# git rm "${f}"`);
    out.push("");
  }
  if (plan.duplicates.length) {
    out.push("# Duplicate files (keep one, re-import the rest)");
    for (const d of plan.duplicates) {
      out.push(`# keep:   ${d.keep}`);
      for (const r of d.remove) out.push(`# git rm "${r}"`);
    }
    out.push("");
  }
  out.push("Write-Host 'dead-doctor cleanup complete — re-run: npx dead-doctor'");
  return out.join("\n");
}

export function renderMarkdown(plan, stats, graphStats) {
  const reclaimable = graphStats?.reclaimableKb ?? 0;
  const lines = [
    "# dead-doctor — Cleanup Plan",
    "",
    `Generated ${new Date().toISOString()} by [dead-doctor](https://noctisnova.com).`,
    "",
    `**Reclaimable space:** ~${reclaimable} KB across ${plan.deletions.length} dead/empty file${plan.deletions.length !== 1 ? "s" : ""}` +
    `${plan.duplicates.length ? ` + ${plan.duplicates.length} duplicate group${plan.duplicates.length !== 1 ? "s" : ""}` : ""}.`,
    "",
    "> Nothing here runs automatically. Review, then run `dead-doctor-cleanup.sh` (or `.ps1`).",
    "> Every deletion goes through `git rm`, so `git checkout .` undoes all of it.",
    "",
  ];

  if (plan.deletions.length) {
    lines.push("## 1. Delete dead & empty files", "");
    for (const d of plan.deletions) lines.push(`- [ ] \`${d.file}\` — ${d.why}`);
    lines.push("");
  }
  if (plan.depRemovals.length) {
    lines.push("## 2. Uninstall zombie dependencies", "", "```bash", `npm uninstall ${plan.depRemovals.join(" ")}`, "```", "");
  }
  if (plan.duplicates.length) {
    lines.push("## 3. Collapse duplicate files", "");
    for (const d of plan.duplicates) {
      lines.push(`- [ ] Keep \`${d.keep}\`, delete ${d.remove.map((r) => `\`${r}\``).join(", ")} and import from the kept copy.`);
    }
    lines.push("");
  }
  if (plan.deadPages.length) {
    lines.push("## 4. Dead pages (confirm unlinked first)", "");
    for (const f of plan.deadPages) lines.push(`- [ ] \`${f}\` — remove the page plus any sibling \`layout\`/\`loading\`/\`error\` files.`);
    lines.push("");
  }

  lines.push("## 5. Manual code edits", "");
  lines.push(`- ${plan.manual.unusedExports} unused export${plan.manual.unusedExports !== 1 ? "s" : ""} — remove the \`export\` (or the whole symbol).`);
  lines.push(`- ${plan.manual.unusedImports} file${plan.manual.unusedImports !== 1 ? "s" : ""} with unused imports — delete the import bindings.`);
  lines.push(`- ${plan.manual.commentBlocks} commented-out block${plan.manual.commentBlocks !== 1 ? "s" : ""} — delete them (git keeps history).`);
  lines.push(`- ${plan.manual.unreachable} unreachable block${plan.manual.unreachable !== 1 ? "s" : ""} — likely logic bugs; fix the control flow.`);
  lines.push("", "---", "", "Built by **NoctisNova** · https://noctisnova.com · hello@noctisnova.com");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Write all three files
// ---------------------------------------------------------------------------

export function writeCleanupScripts(projectPath, issues, stats, graphStats) {
  const root = path.resolve(projectPath);
  const plan = buildPlan(issues);

  const files = [
    { name: "dead-doctor-cleanup.sh",  content: renderBash(plan) },
    { name: "dead-doctor-cleanup.ps1", content: renderPowerShell(plan) },
    { name: "dead-doctor-cleanup.md",  content: renderMarkdown(plan, stats, graphStats) },
  ];

  const written = [];
  for (const f of files) {
    const full = path.join(root, f.name);
    try { fs.writeFileSync(full, f.content, "utf-8"); written.push(full); } catch { /* non-fatal */ }
  }
  return { written, plan };
}
